In [1]:
# 1.导入numpy
import numpy as np

In [2]:
# 2.打印numpy版本和配置信息
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
# 3.创建size为10的零向量
v=np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4.显示任何一个数组的内存大小
print("{} bytes".format(v.size*v.itemsize))

80 bytes


In [5]:
# 5.在命令行中获取numpy中add函数的信息
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
# 6.创建1个大小为10的零向量，第五个值修改为1
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7.创建一个从10到49的数组
arr=np.array(list(range(10,50)))
arr1=np.arange(10,50)
print(arr)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 8.倒序一个数组，第一个元素放在最后
arr2=arr1[::-1]
print(arr2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
# 9.创建一个3x3的矩阵，使用0~8

matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 10.找到数组中非零元素的索引
nz=np.nonzero([1,2,0,0,0,4])
narr=np.array([1,2,0,3,0,4])
print(np.where(narr!=0))
print(nz)

(array([0, 1, 3, 5], dtype=int64),)
(array([0, 1, 5], dtype=int64),)


In [11]:
# 11.创建3x3的单位阵
I3=np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 12.创建3x3x3的随机矩阵
matrix3=np.random.random([3,3,3])
print(matrix3)

[[[0.09983825 0.51269703 0.08248495]
  [0.84069441 0.66733366 0.26131436]
  [0.25540608 0.59946855 0.62585562]]

 [[0.08869863 0.16348651 0.22218862]
  [0.86305655 0.76697127 0.93844032]
  [0.60574383 0.45321027 0.97147334]]

 [[0.24106412 0.64653505 0.22477015]
  [0.43078767 0.74578495 0.60615706]
  [0.91813272 0.3315943  0.11909975]]]


In [13]:
# 13.创建10x10的随机矩阵，计算最小值和最大值
matrix=np.random.random([10,10])
maxitem=np.max(matrix)
minitem=np.min(matrix)

print(matrix)
print(maxitem,minitem)
print(matrix.max(),matrix.min())

[[0.52169507 0.54785369 0.77537099 0.91016753 0.47245462 0.77408642
  0.40409561 0.75381954 0.93065131 0.66870963]
 [0.27824747 0.78383732 0.28919323 0.13439172 0.12840986 0.11250968
  0.40113547 0.24208421 0.6162084  0.14623753]
 [0.99714061 0.38175844 0.74612004 0.92253764 0.92119831 0.96458652
  0.09675281 0.54381738 0.74725166 0.21816254]
 [0.03407789 0.39759261 0.92742133 0.65590942 0.63217703 0.25204496
  0.00571671 0.41731774 0.65030681 0.42987932]
 [0.51098057 0.47751892 0.39722897 0.53875578 0.83796968 0.43453355
  0.31785473 0.21552828 0.87000044 0.49606952]
 [0.20244167 0.52933279 0.67668956 0.21287256 0.92286022 0.02348486
  0.49434482 0.5152124  0.60625275 0.72889013]
 [0.3048818  0.41088043 0.58135127 0.23540166 0.33562178 0.54511384
  0.6823925  0.79448877 0.83650202 0.57517623]
 [0.47087255 0.42928751 0.60712518 0.61599576 0.87524424 0.55852663
  0.15526226 0.55944325 0.68168268 0.81556343]
 [0.75697283 0.59052732 0.90949637 0.87524475 0.47507973 0.89352354
  0.9443436 

In [14]:
# 14.创建大小为30的数组，求均值
arr=np.random.random(30)

print(arr)
print(arr.mean())
print(np.average(arr))

[0.12428357 0.1991966  0.91071527 0.30720862 0.08065127 0.01715599
 0.86055276 0.00449018 0.03378888 0.92094388 0.06713983 0.63862384
 0.46837801 0.27714251 0.02568365 0.7293785  0.35285421 0.72376176
 0.88040191 0.64908236 0.60372581 0.98644981 0.33148771 0.82006255
 0.23266252 0.81170201 0.25132302 0.89073091 0.50972043 0.74727197]
0.4818856780096776
0.4818856780096776


In [15]:
# 15.创建一个矩阵，最外面是1，里面是0

matrix=np.ones([10,10])
matrix[1:-1,1:-1]=0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# 16.在已存在的矩阵中添加1圈0
z=np.ones([4,4])
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
# 17.下列表达式的值

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
# 18.对角线下方写1，2，3，4
matrix=np.diag(1+np.arange(4),k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
# 19.创建一个8x8大小的棋盘格
Z=np.zeros([8,8])
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
# 20.创建一个6x7x8形状的数组，指出第100个数的位置
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [21]:
np.info(np.tile)

 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an a

In [22]:
# 21.使用tile函数创建8x8的棋盘格
Z=np.tile(np.array([[1,0],[0,1]]),[4,4])
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [23]:
# 22.标准化一个5x5的随机矩阵

matrix=np.random.random([5,5])
norm_matrix=(matrix-matrix.mean())/matrix.std()

print(norm_matrix)

[[-0.31092465 -0.58577543  2.19977116  0.00512286  0.13448742]
 [-1.16192288  1.48690318 -0.86655113  1.1227793  -0.49492234]
 [ 0.38696154 -1.46255095 -0.11237013 -0.02564946 -0.68080541]
 [ 1.49218231 -0.45396982 -1.48370031  0.50721552  0.02899842]
 [ 0.6958926   1.06132718  1.10494808 -1.13740982 -1.45003726]]


In [24]:
matrix.std(),matrix.mean(),np.std(matrix),np.mean(matrix)

(0.25043046015883447,
 0.3901519386953658,
 0.25043046015883447,
 0.3901519386953658)

In [25]:
# 23.创建一个自定义类型描述无符号类型RGBA

color=np.dtype([("r", np.ubyte),
                ("g", np.ubyte),
               ("b", np.ubyte),
               ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [26]:
# 24.矩阵相乘 5x3和3x2

A=np.arange(15).reshape(5,3)
B=np.arange(6).reshape(3,2)
C=np.dot(A,B)

print(C)
print(A@B)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [27]:
# 25.用负数替换一维数组中介于3到8之间的元素

Z=np.arange(11)
Z[(Z>3) & (Z<8)]=-1*Z[(Z>3) & (Z<8)]

print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [28]:
# 26.代码输出结果

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # negative it counts from the last to the first axis.

9
10


In [29]:
np.info(np.sum)

 sum(*args, **kwargs)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same precision as the platform integer is used.
out : ndarray, optional


In [30]:
np.info(np.ones)

 ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
       [1.]])

>>> s = (2,2

In [31]:
# 27.Z为整数向量，下列哪些表达式是合法的

Z=np.ones((5,), dtype=int)

print(Z**Z)
print(2 << Z >> 2) 
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
Z=np.ones((5,), dtype=int)
print(Z<Z>Z) #ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[1 1 1 1 1]
[1 1 1 1 1]
[False False False False False]
[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
[1. 1. 1. 1. 1.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
# 28.下列表达式的结果

print(np.array(0) / np.array(0)) #nan
print(np.array(0) // np.array(0)) #0
print(np.array([np.nan]).astype(int).astype(float)) #[-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


In [33]:
# 29.

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 5.  9. -8.  8. -2. -4. -3.  3. -8.  5.]
[ 5.  9. -8.  8. -2. -4. -3.  3. -8.  5.]


In [34]:
# 30.找出两个数组之间的共同值
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)

print(Z1,Z2,np.intersect1d(Z1,Z2))

[9 5 7 9 8 4 4 8 0 4] [0 8 1 8 2 8 9 8 8 3] [0 8 9]


In [35]:
# 31. 如何忽略所有numpy的warning
defaults = np.seterr(all="ignore")
Z=np.ones(1)/0

# Back to sanity
_ = np.seterr(**defaults)

with np.errstate(all = "ignore"):
    np.arange(3)/0

In [37]:
# 32. 以下表达式是否正确？
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [39]:
# 33. 如何获得昨天、今天和明天的日期？

yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

print(yesterday, today, tomorrow)

2021-09-21 2021-09-22 2021-09-23


In [40]:
# 34. 如何获得与2016年7月对应的所有日期？

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [41]:
# 35. 如何计算（A+B） * （-A/2) (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [42]:
# 36. 使用4种不同的方法提取随机均匀分布的整数部分

Z = np.random.uniform(0, 10, 10)

print(Z - Z%1)
print(Z//1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[2. 7. 6. 0. 6. 2. 3. 2. 9. 4.]
[2. 7. 6. 0. 6. 2. 3. 2. 9. 4.]
[2. 7. 6. 0. 6. 2. 3. 2. 9. 4.]
[2 7 6 0 6 2 3 2 9 4]
[2. 7. 6. 0. 6. 2. 3. 2. 9. 4.]


In [43]:
# 37. 创建行值从0到4的5x5矩阵

Z = np.zeros((5,5))
Z+=np.arange(5)
print(Z)

Z=np.tile(np.arange(0,5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [44]:
# 38. 考虑生成10个整数的生成器函数，并将其用于构建序列

def generate():
    for x in range(10):
        yield x

Z=np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [47]:
# 39. 创建大小10的矢量，其值范围从0到1不等

Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [49]:
# 40. 创建大小10的随机向量并进行排序
Z=np.random.random(10)
print(sorted(Z))
Z.sort()
print(Z)

[0.06047274066082209, 0.21833091195205445, 0.24283359229381718, 0.3683754374293806, 0.4775895400475709, 0.5614822034079601, 0.5623177712349778, 0.619077854025258, 0.7425620818600607, 0.7564528703381521]
[0.06047274 0.21833091 0.24283359 0.36837544 0.47758954 0.5614822
 0.56231777 0.61907785 0.74256208 0.75645287]


In [50]:
# 41. 如何比np.sum更快地对小矩阵求和

Z=np.arange(10)
np.add.reduce(Z)

45

In [51]:
# 42.考虑两个随机矩阵A和B，判断它们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


False
False


In [52]:
# 43. 使阵列不可变（仅限读取）

Z=np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [53]:
# 44. 考虑代表手推车坐标的随机10x2矩阵，将其转换为极地坐标

Z=np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.86371697 0.40279497 0.26972903 1.03989421 1.36761404 0.43907733
 0.83679117 0.51951806 0.73199189 0.9229393 ]
[1.10405097 0.51515879 0.92439293 0.7659597  0.81289884 1.46589447
 0.62190039 0.07382623 0.26699742 0.2173574 ]


In [55]:
# 45. 创建大小10的随机向量，将其最大值替换为0

Z = np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.59764649 0.43495709 0.25822819 0.22273076 0.07085335 0.97882461
 0.1592912  0.00399914 0.42885781 0.3822565 ]
[0.59764649 0.43495709 0.25822819 0.22273076 0.07085335 0.
 0.1592912  0.00399914 0.42885781 0.3822565 ]


In [56]:
# 46. 创建一个结构化序列，其坐标覆盖[0,1] X [0,1] 区域
Z = np.zeros((5,5), [('x',float), ('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [57]:
# 47. 给出两个数组X和Y，组建柯西矩阵C(Cij= 1/(xi-yj))

X = np.arange(8)
Y = X +0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [61]:
# 48. 打印每个numpy数值类型的最小和最大值

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [62]:
# 49. 如何打印阵列的所有值？
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
# 50.如何在向量中找到最接近的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

59


In [64]:
# 51. 创建一个结构化阵列，表示位置（x,y)和颜色（r,g,b）
Z = np.zeros(10, [('position',[ ('x', float, 1),
                               ('y', float,1)]),
                  ('color', [('r', float,1),
                            ('g',float,1),
                            ('b',float,1)])])

C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [3]:
# 52. 考虑形状（100，2）表示坐标的随机向量，逐点查找距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

# use with scipy
import scipy
import scipy.spatial

Z=np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.57560759 0.39023454 0.45722474 0.48136865 1.02552665
  0.394547   1.07464473 0.1325219  0.86049316]
 [0.57560759 0.         0.30829207 0.20323604 0.44563473 0.48294717
  0.45526071 0.54823072 0.45299716 0.29945339]
 [0.39023454 0.30829207 0.         0.35441824 0.55887173 0.66226755
  0.1488614  0.7012151  0.26103801 0.60078452]
 [0.45722474 0.20323604 0.35441824 0.         0.24677558 0.68002943
  0.49435142 0.74843126 0.3624269  0.42085572]
 [0.48136865 0.44563473 0.55887173 0.24677558 0.         0.90545876
  0.67747588 0.9782963  0.4500773  0.59193091]
 [1.02552665 0.48294717 0.66226755 0.68002943 0.90545876 0.
  0.75980004 0.08040076 0.89399095 0.37479088]
 [0.394547   0.45526071 0.1488614  0.49435142 0.67747588 0.75980004
  0.         0.78691701 0.29133556 0.74264043]
 [1.07464473 0.54823072 0.7012151  0.74843126 0.9782963  0.08040076
  0.78691701 0.         0.94233742 0.45519157]
 [0.1325219  0.45299716 0.26103801 0.3624269  0.4500773  0.89399095
  0.29133556 0.94233

In [4]:
# 53. 将float32数据转换为int32

Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[77 44 23  1  7 87 86 21 49 29]


In [17]:
# 54. 如何阅读以下文件
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11
    
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [19]:
# 55. numpy中类似于enumerate的功能
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [20]:
# 56. 生成通用的 2D 高斯式阵列
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [21]:
# 57. 如何随机将p元素放置在2D阵列中？
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
# 58.
A = np.array([[1,2,3],[1,2,3]])
print(A-A.mean(axis=1,keepdims=True))

[[-1.  0.  1.]
 [-1.  0.  1.]]


In [22]:
# 58. 减去矩阵每行的平均值
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.5423359   0.54026813  0.03027683 -0.33265228 -0.12286739  0.11470862
  -0.42660457 -0.06715473  0.14853914 -0.42684967]
 [ 0.36033656 -0.36113209 -0.32367177  0.13577074  0.50502365  0.01610311
   0.53071394 -0.24215364 -0.24268256 -0.37830793]
 [-0.14295821  0.056936   -0.18197869  0.50655708  0.031724    0.21187453
   0.1205751  -0.47353848 -0.31670443  0.18751309]
 [ 0.16995725  0.36901802 -0.2726128  -0.30888983  0.16458394  0.17692917
   0.13297397  0.18726306 -0.31342565 -0.30579711]
 [ 0.37230186 -0.30543337  0.30252074  0.01855017  0.01919633  0.14038977
  -0.18699221  0.16903956  0.0260839  -0.55565675]]


In [28]:
# 59. 如何按第n列对阵列进行排序
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 8 0]
 [2 3 8]
 [9 6 7]]
[[2 3 8]
 [9 6 7]
 [7 8 0]]


In [29]:
# 60. 如何判断给定2D阵列是否有空列？
Z = np.random.randint(0, 3, (3,10))
print((~Z.any(axis=0)).any())

False


In [30]:
# 61. 从阵列中的给定值中查找最接近值
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.4766362906774271


In [33]:
# 62. 考虑两个具有形状（1， 3）和（3，  1）的阵列，
# 如何计算传动器计算其总和？
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...]= x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [34]:
# 63. 创建具有名称属性的阵列类
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: 
            return
        self.info = getattr(obj, 'name', "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [3]:
# 64. 考虑给定向量，如何向第二个向量索引的每个元素添加1
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 6. 4. 3. 1. 2. 4. 2. 4. 1.]


In [7]:
# 65. 如何根据索引列表（I）将向量（X)的元素累积到阵列（F）中？
X = [10,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)
print(np.bincount(I))
# np.info(np.bincount)
# 计算数组I的直方图

[ 0. 16.  0.  6.  5.  0.  0.  0.  0.  3.]
[0 2 0 2 1 0 0 0 0 1]


In [9]:
# 66. 考虑（w, h, 3）图像（dtype+u8）， 计算唯一颜色的数量
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1,3), axis=0)
n =len(colors)
print(n)

64


In [11]:
# 67. 考虑四维阵列，如何同时获得最后两个轴的总和？
A = np.random.randint(0,10,(3,4,3,4))
sum_res = A.sum(axis=(-2,-1))
# print(A,sum_res)

In [12]:
# 68. 考虑到一维向量D, 如何使用描述子集指数的
# 相同大小的向量S来计算D子集的手段？
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.39382027 0.74521417 0.59254491 0.70766511 0.62724774 0.53716617
 0.85273455 0.37304446 0.40835536 0.61432411]


In [14]:
# 69.如何获得点积结果的对角线？
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# slow version
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))

# Faster version
print(np.einsum("ij,ji->i",A,B))

[1.87760825 0.7921981  1.86055578 1.25655145 1.5611091 ]
[1.87760825 0.7921981  1.86055578 1.25655145 1.5611091 ]
[1.87760825 0.7921981  1.86055578 1.25655145 1.5611091 ]


In [15]:
# 70. 考虑向量[1、2、3、4、5]，如何构建每个值之间连续3个零的向量？
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros([len(Z) + (len(Z)-1)*(nz)])
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [19]:
# 71. 考虑一个维度阵列（5，5，3），如何用一个具有维度的阵列
# （5，5）来覆盖它
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [20]:
# 72. 如何交换两行阵列？
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
# 交换两列
A= np.array([[1,2,3],[2,3,4],[1,6,5], [9,3,4]])
A[:,[0,1,2]]=A[:,[1,0,2]]
print(A)

[[2 1 3]
 [3 2 4]
 [6 1 5]
 [3 9 4]]


In [21]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments 
# composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0', F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 1, 36) ( 1, 49) ( 3, 49) ( 3, 82) ( 4, 38) ( 4, 80) ( 8, 54) ( 8, 88)
 ( 9, 20) ( 9, 89) (10, 28) (10, 55) (20, 89) (22, 65) (22, 80) (28, 55)
 (33, 35) (33, 38) (34, 57) (34, 64) (35, 38) (36, 49) (38, 80) (49, 82)
 (54, 88) (57, 64) (60, 63) (60, 91) (63, 91) (65, 80)]


In [25]:
# 74. 给定排序阵列C对应于bin计数，如何生成一个阵列A，
# 以便np.bincount(A) == C ?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(C,A)
# np.info(np.repeat)

[0 2 1 1 2 0 1] [1 1 2 3 4 4 6]


In [30]:
# 75. 如何使用阵列的滑动窗口计算平均值？
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n

Z = np.arange(1,10)
print(moving_average(Z))

[2. 3. 4. 5. 6. 7. 8.]


In [7]:
# 76. 考虑一维阵列，构建第一行为（Z[0], Z[1], Z[2])的
# 二维阵列，随后每行按1（最后一行应为（Z[-3], Z[-2], Z[-1])
from numpy.lib import stride_tricks

def rolling(a,window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(1,13), 3)
print(Z)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


In [8]:
# 77.  How to negate a boolean, or 
# to change the sign of a float inplace?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out=Z)

array([-0.70000372,  0.27024069,  0.30651292,  0.60683004, -0.86634056,
       -0.30429294, -0.98783146, -0.40091017,  0.68789975,  0.77036623,
        0.37056338, -0.45909827, -0.78149964,  0.37625326, -0.06188092,
        0.87267217,  0.30176616,  0.12156639,  0.30243081,  0.0380749 ,
        0.25514159,  0.90695843,  0.64384985, -0.12739586,  0.84215652,
       -0.26296235,  0.63342643,  0.03950033,  0.74089875, -0.62321584,
        0.78759223, -0.81245328, -0.52749355, -0.82198402, -0.7728279 ,
        0.68044754, -0.6640864 , -0.75612286,  0.92141623,  0.12674575,
       -0.28678511,  0.6795656 , -0.89914034,  0.47947803,  0.05123668,
       -0.19214293,  0.19137466,  0.01152767, -0.93611789,  0.63528473,
       -0.59172264, -0.65802928,  0.54918485, -0.51607459,  0.44010472,
        0.68433652,  0.0783354 , -0.3605115 , -0.27473763, -0.75315603,
        0.31567271,  0.95532391, -0.05300044,  0.33086186,  0.10147016,
        0.16322864,  0.94885662, -0.66268224, -0.65964666, -0.76

In [10]:
# 78. 考虑2组点P0、P1描述行（2d）和点p,如何计算从p到每行i
# (P0[i], P1[i])的距离？
def distance(P0,P1,p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/ L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(P0, P1, p))

[ 1.13996467  2.08532152  6.19802281  2.33813986  3.22298612  5.66682088
  6.31845411 10.16311897 11.5846396   4.2899508 ]


In [11]:
# 79. 考虑2组点P0,P1描述行（2d)和一组点P,如何计算从每个点
# j(P[j])到每行i(P0[i],P1[i])的距离？
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.13952727e+01 2.10083275e+00 1.00032837e+01 3.86174135e+00
  3.70473597e+00 4.22226375e+00 2.72827481e+00 2.90974900e-03
  7.21543613e+00 9.61426971e-01]
 [2.47863423e+00 1.23862974e+01 1.84538492e-01 8.96040827e+00
  1.84252765e+00 8.67086323e+00 7.32136285e+00 1.91762381e+00
  4.04517418e+00 9.19006241e+00]
 [1.13780238e+01 2.37718803e+00 9.72460703e+00 3.67605047e+00
  4.04822064e+00 4.30913998e+00 2.44640573e+00 3.54274971e-01
  6.85955243e+00 1.16633409e+00]
 [5.71303322e-01 1.15674087e+01 5.99518635e-01 7.07051837e+00
  4.14405239e+00 5.27345246e+00 6.58609140e+00 3.43680889e+00
  2.81634087e+00 5.76816181e+00]
 [9.85690561e+00 3.69882926e+00 1.58780954e+01 6.90975687e+00
  5.60718066e+00 8.29835712e-02 8.70699286e+00 9.13229574e+00
  1.61310796e+01 5.89203264e+00]
 [8.48324171e-01 1.89935526e+01 6.89930567e+00 1.17295390e+01
  1.41937528e+01 2.03641319e+00 1.41850838e+01 1.36714875e+01
  7.31072578e+00 7.32984892e-01]
 [8.31871831e+00 1.24322681e+01 3.81114485e-01 4.16655013e

In [ ]:
# 80. 考虑任意阵列，编写一个功能，提取具有固定形状的
# 子部分，并以给定元素为中心（必要时具有值的垫片）

Z = 